// Regenerates electron/tlds.mjs: the list of real top-level domains, used to tell "nodejs.org" (a website) from
// "package.json" (a search). Source: the Public Suffix List, https://publicsuffix.org/list/ (MPL-2.0).
//   node scripts/update-tlds.mjs
// Only the ICANN section is used, and only single-label entries, which are exactly the top-level domains.
import { domainToASCII } from "node:url";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE = "https://publicsuffix.org/list/public_suffix_list.dat";
const res = await fetch(SOURCE, { signal: AbortSignal.timeout(30000) });
if (!res.ok) throw new Error(`Could not download ${SOURCE}: HTTP ${res.status}`);
const text = await res.text();

const begin = text.indexOf("// ===BEGIN ICANN DOMAINS===");
const end = text.indexOf("// ===END ICANN DOMAINS===");
if (begin === -1 || end === -1) throw new Error("The list format changed: ICANN section markers not found");

const tlds = new Set();
for (const raw of text.slice(begin, end).split("\n")) {
  const line = raw.trim();
  if (!line || line.startsWith("//") || line.startsWith("!") || line.startsWith("*") || line.includes(".")) continue;
  const ascii = domainToASCII(line);
  if (ascii) tlds.add(ascii);
}
if (tlds.size < 1000 || !tlds.has("com") || !tlds.has("org")) throw new Error(`Suspicious result: ${tlds.size} entries`);

const sorted = [...tlds].sort();
const out = `// Top-level domains, generated by scripts/update-tlds.mjs from the Public Suffix List (ICANN section).
// Source: ${SOURCE}
// Entries: ${sorted.length}
//
// This file contains data from the Public Suffix List, which is licensed under the Mozilla Public License, v. 2.0.
// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was
// not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/. The licence text is in
// LICENSES/MPL-2.0.txt.
//
// SPDX-License-Identifier: MPL-2.0

export const TLDS = new Set([
${sorted.map((t) => `  "${t}",`).join("\n")}
]);
`;
const file = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "electron", "tlds.mjs");
fs.writeFileSync(file, out);
console.log(`wrote ${file}: ${sorted.length} top-level domains`);
